version: "3.8"

services:
  server:
    build: ./server
    container_name: mmo-server
    restart: unless-stopped
    networks:
      - mmo-net

  client:
    build: ./client
    container_name: mmo-client
    restart: unless-stopped
    environment:
      - VITE_API_URL=/api
    networks:
      - mmo-net
    depends_on:
      - server

  nginx:
    image: nginx:latest
    container_name: mmo-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d:ro  # monte le dossier entier
    networks:
      - mmo-net
    depends_on:
      - client
      - server

networks:
  mmo-net:
    driver: bridge
